

name: "CI Golang"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.16.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go mod download

      - name: Run go vet # -tags debug because it will fail on variables like: FileMainBundleMinJS in httphandlersprod.go
        run: |
          go vet -tags debug .

      - name: Run tests
        run: |
          go test -tags debug -v
